server:
    port: 8088

beetl:
    DELIMITER_STATEMENT_START: \@    # "\"会在BeetlProperties设置的时候去掉
    DELIMITER_STATEMENT_END: null
    resource-auto-check: true       #热加载beetl模板，开发时候用
    templatesPath: templates

spring:
    http:
        log-request-details: false
    application:
        name: xin
    profiles:
        active: @spring.active@
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        generate-ddl: false
        open-in-view: false

logging:
    level:
        web: debug

---
spring:
    profiles: local
    datasource:
        druid:
            master:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://10.100.21.61:3306/xin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
                username: root
                password: 123456
                max-active: 20
                min-idle: 5
                max-wait: 60000
                validation-query: SELECT 1 FROM DUAL
                validation-query-timeout: 100000
                test-on-borrow: false
                test-on-return: false
                test-while-idle: true
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                # filters: stat,wall,log4j
                log-slow-sql: true
            quartz:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://10.100.21.61:3306/quartz?useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 123456
                max-active: 20
                min-idle: 5
                max-wait: 60000
                validation-query: SELECT 1 FROM DUAL
                validation-query-timeout: 100000
                test-on-borrow: false
                test-on-return: false
                test-while-idle: true
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                # filters: stat,wall,log4j
                log-slow-sql: true
    quartz:
        wait-for-jobs-to-complete-on-shutdown: true
        # scheduler-name: xinScheduler
        startup-delay: 4s
        overwrite-existing-jobs: false
        auto-startup: true
        job-store-type: jdbc
        jdbc:
            initialize-schema: never
            # schema: classpath:org/quartz/impl/jdbcjobstore/tables_@@platform@@.sql
        properties:
            org:
                quartz:
                    scheduler:
                        instanceName: unClusteredScheduler
                        instanceId: AUTO
                    jobStore:
                        class: org.quartz.impl.jdbcjobstore.JobStoreTX
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        isClustered: false
                        useProperties: true
                        tablePrefix: QRTZ_
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        threadCount: 6
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true


---
spring:
    profiles: dev
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: berrybio


---
spring:
    profiles: test
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root


---
spring:
    profiles: produce
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root





